CREATE TABLE abilities_changes_effects_text_lang (
    id INTEGER PRIMARY KEY,
    effect VARCHAR(1000) NOT NULL,
    ability_change_id INTEGER,
    language_id INTEGER,
    FOREIGN KEY (ability_change_id) REFERENCES abilities_changes(id),
    FOREIGN KEY (language_id) REFERENCES languages(id)
);

INSERT INTO abilities_changes_effects_text_lang (id, effect, ability_change_id, language_id) VALUES 
(1, 'Hat im Kampf keinen Effekt.', 1, 6),
(2, 'Has no effect in battle.', 1, 9),
(3, 'Verhindert keine regulären K.O. bei vollen hp.', 2, 6),
(4, 'Does not prevent regular KOs from full HP.', 2, 9),
(5, 'Hat außerhalb vom Kampf keinen Effekt.', 3, 6),
(6, 'Has no overworld effect.', 3, 9),
(7, 'electric-Attacken die keinen Schaden anrichten, wie thunder wave, werden nicht absorbiert.', 4, 6),
(8, 'Does not absorb non-damaging electric moves, i.e. thunder wave.', 4, 9),
(9, 'Löst bei Attacken die mehrmals Treffen bei jedem Treffer aus.', 5, 6),
(10, 'Triggers on every hit of multiple-hit moves.', 5, 9),
(11, 'will o wisp triggert die Fähigkeit nicht bei Pokémon die immun gegen burn sind.', 6, 6),
(12, 'will o wisp does not trigger this ability for Pokémon immune to burns.', 6, 9),
(13, 'Hat außerhalb vom Kampf keinen Effekt.', 7, 6),
(14, 'Has no overworld effect.', 7, 9),
(15, 'Hat außerhalb vom Kampf keinen Effekt.', 8, 6),
(16, 'Has no overworld effect.', 8, 9),
(17, 'Hat keinen Effekt, wenn die Fähigkeit nach Kampfbeginn erlangt wurde.', 9, 6),
(18, 'Does not take effect if acquired after entering battle.', 9, 9),
(19, 'Betrifft andere Pokémon mit dieser Fähigkeit.', 10, 6),
(20, 'Affects other Pokémon with this ability.', 10, 9),
(21, 'Verursacht nur 1/16 der maximalen hp des Angreifers Schaden.', 11, 6),
(22, 'Inflicts only 1/16 of the attacker''s maximum HP in damage.', 11, 9),
(23, 'fire fang und Attacken die typenlosen Schaden verursachen, ignorieren diese Fähigkeit unabhängig von ihrem Typ.', 12, 6),
(24, 'fire fang and moves that inflict typeless damage ignore this ability regardless of type.', 12, 9),
(25, 'Hat außerhalb vom Kampf keinen Effekt.', 13, 6),
(26, 'Has no overworld effect.', 13, 9),
(27, 'Kann das Wesen von Pokémon mit denen in der Spielwelt interagiert wird nicht verändern.', 14, 6),
(28, 'Cannot influence the natures of Pokémon encountered by interacting with them on the overworld.', 14, 9),
(29, 'Gibt schwere poison als normale poison zurück.', 15, 6),
(30, 'Passes back bad poison as regular poison.', 15, 9),
(31, 'Hat außerhalb vom Kampf keinen Effekt.', 16, 6),
(32, 'Has no overworld effect.', 16, 9),
(33, 'Betrifft keine electric-Attacken die keinen Schaden anrichten, wie thunder wave. Erhöht die Anzahl an Trainer-Anrufen wenn irgendein Pokémon im Team diese Fähigkeit hat.', 17, 6),
(34, 'Does not affect non-damaging electric moves, i.e. thunder wave. Increases the frequency of Match Call calls on the overworld if any party Pokémon has this ability.', 17, 9),
(35, 'Leitet electric-Attacken um, ohne ihre Effekte zu deaktivieren oder einen special attack Bonus zu gewähren. Leitet hidden power nicht um.', 18, 6),
(36, 'Redirects electric moves without negating them or granting any Special Attack boost. Does not redirect hidden power.', 18, 9),
(37, 'Hat außerhalb vom Kampf keinen Effekt.', 19, 6),
(38, 'Has no overworld effect.', 19, 9),
(39, 'Hat außerhalb vom Kampf keinen Effekt.', 20, 6),
(40, 'Has no overworld effect.', 20, 9),
(41, 'Hindert heal bell daran, das Pokémon zu heilen, auch außerhalb vom Kampf.', 21, 6),
(42, 'Prevents heal bell from curing the Pokémon, whether or not it is in battle.', 21, 9),
(43, 'Hat außerhalb vom Kampf keinen Effekt.', 22, 6),
(44, 'Has no overworld effect.', 22, 9),
(45, 'Betrifft keine Attacken von Teammitgliedern die alle anderen Pokémon als Ziel haben. Diese Fähigkeit wird im Kampf nicht angekündigt.', 23, 6),
(46, 'Does not affect friendly Pokémon''s moves that target all other Pokémon. This ability''s presence is not announced upon entering battle.', 23, 9),
(47, 'Hat außerhalb vom Kampf keinen Effekt.', 24, 6),
(48, 'Has no overworld effect.', 24, 9),
(49, 'Hat außerhalb vom Kampf keinen Effekt.', 25, 6),
(50, 'Has no overworld effect.', 25, 9),
(51, 'Hat außerhalb vom Kampf keinen Effekt.', 26, 6),
(52, 'Has no overworld effect.', 26, 9),
(53, 'Verdoppelt den Radius in dem cut Gras entfernt, wenn irgendein Pokémon im Team diese Fähigkeit hat.', 27, 6),
(54, 'Doubles cut''s grass-cutting radius on the overworld if any party Pokémon has this ability.', 27, 9),
(55, 'Hat im Kampf keinen Effekt.', 28, 6),
(56, 'Has no effect in battle.', 28, 9),
(57, 'Hat außerhalb vom Kampf keinen Effekt.', 29, 6),
(58, 'Has no overworld effect.', 29, 9),
(59, 'Hat außerhalb vom Kampf keinen Effekt.', 30, 6),
(60, 'Has no overworld effect.', 30, 9),
(61, 'Hat außerhalb vom Kampf keinen Effekt.', 31, 6),
(62, 'Has no overworld effect.', 31, 9),
(63, 'Hat keinen Effekt während das Pokémon schläft.', 32, 6),
(64, 'Does not take effect during sleep.', 32, 9),
(65, 'Hat außerhalb vom Kampf keinen Effekt.', 33, 6),
(66, 'Has no overworld effect.', 33, 9),
(67, 'Erhöht die Anzahl an Rufen die man außerhalb vom Kampf hört, wenn irgendein Pokémon im Team diese Fähigkeit hat.', 34, 6),
(68, 'Increases the frequency of cries heard on the overworld if any party Pokémon has this ability.', 34, 9),
(69, 'Hat außerhalb vom Kampf keinen Effekt.', 35, 6),
(70, 'Has no overworld effect.', 35, 9),
(71, 'Hat außerhalb vom Kampf keinen Effekt.', 36, 6),
(72, 'Has no overworld effect.', 36, 9),
(73, 'Hat außerhalb vom Kampf keinen Effekt.', 37, 6),
(74, 'Has no overworld effect.', 37, 9),
(75, 'Poison schadet dem Pokémon außerhalb vom Kampf.', 38, 6),
(76, 'Poison still damages the Pokémon outside of battle.', 38, 9),
(77, 'Paralysis hindert das Pokémon nicht daran sich zu bewegen, aber der Speed Malus bleibt. Poison schadet dem Pokémon außerhalb vom Kampf.', 39, 6),
(78, 'Paralysis cannot prevent the Pokémon from moving, though the Speed cut is unaffected. Poison still damages the Pokémon outside of battle.', 39, 9),
(79, 'Wegen eines Glitches haben Attacken die von dieser Fähigkeit beeinflusst sind eine (100 - Genauigkeit)% Chance durch den Detect oder Protect zu treffen.', 40, 6),
(80, 'Due to a glitch, moves affected by this ability have a (100 - accuracy)% chance to hit through Detect or Protect.', 40, 9),
(81, 'Rest funktioniert normal bei starkem Sonnenlicht.', 41, 6),
(82, 'Rest works as usual during strong sunlight.', 41, 9),
(83, 'Fling kann normal benutzt werden.', 42, 6),
(84, 'Fling can be used as usual.', 42, 9),
(85, 'Leitet Water-Attacken um ohne den Special Attack Bonus zu gewähren. Leitet Hidden Power nicht um.', 43, 6),
(86, 'Redirects water moves without negating them or granting any Special Attack boost. Does not redirect Hidden Power.', 43, 9),
(87, 'Kann Flower Gift und Wonder Guard kopieren.', 44, 6),
(88, 'Can copy Flower Gift and Wonder Guard.', 44, 9),
(89, 'Kann Forecast und Trace kopieren.', 45, 6),
(90, 'Can copy Forecast and Trace.', 45, 9),
(91, 'Funktioniert nur wenn es mit Minus kombiniert wird.', 46, 6),
(92, 'Powers up only when paired with Minus.', 46, 9),
(93, 'Funktioniert nur wenn es mit Plus kombiniert wird.', 47, 6),
(94, 'Powers up only when paired with Plus.', 47, 9),
(95, 'Die Chance, dass der Effekt eintritt, beträgt 30%.', 48, 6),
(96, 'Chance of taking effect is 30%.', 48, 9),
(97, 'Triple Kick wird nicht beeinflusst.', 49, 6),
(98, 'Triple Kick is unaffected.', 49, 9),
(99, 'Struggle wird nicht beeinflusst. Helping Hand und Defense Curl werden nicht beachtet.', 50, 6),
(100, 'Struggle is unaffected. Helping Hand and Defense Curl are not taken into account.', 50, 9),
(101, 'Hat außerhalb vom Kampf keinen Effekt.', 51, 6),
(102, 'Has no overworld effect.', 51, 9),
(103, 'Die Chance, dass der Effekt eintritt, beträgt 33%.', 52, 6),
(104, 'Chance of taking effect is 33%.', 52, 9);
