CREATE TABLE contests_effects_effects_text_lang (
    id INT PRIMARY KEY,
    effect VARCHAR(2000) NOT NULL,
    contest_effect_id INT,
    language_id INT,
    FOREIGN KEY (contest_effect_id) REFERENCES contests_effects(id),
    FOREIGN KEY (language_id) REFERENCES languages(id)
);


INSERT INTO contests_effects_effects_text_lang (id, effect, contest_effect_id, language_id) VALUES 
(1, 'Gives a high number of appeal points wth no other effects.', 1, 9),
(2, 'If the Pokémon that appealed before the user earned less than three appeal points, user earns six; if three, user earns three; if more than three, user earns none.', 2, 9),
(3, 'If the user is jammed this turn after using this move, it will receive twice as many jam points.', 3, 9),
(4, 'Attempts to jam the Pokémon that appealed before the user.', 4, 9),
(5, 'Attempts to jam all Pokémon that have appealed this turn.', 5, 9),
(6, 'Attempts to jam the other Pokémon. The user cannot make an appeal on the next turn, but it cannot be jammed either.', 6, 9),
(7, 'User cannot make any more appeals for the remainder of the contest.', 7, 9),
(8, 'Attempts to jam all Pokémon that have appealed this turn.', 8, 9),
(9, 'Attempts to jam the Pokémon that appealed before the user.', 9, 9),
(10, 'Attempts to jam all Pokémon that have appealed this turn. If a Pokémon is in combo standby status, it is jammed 5 points instead of 1.', 10, 9),
(11, 'If the Applause meter is empty or at one, earns one point; if two, earns three points; if three, earns four points; if four, earns six points.', 11, 9),
(12, 'If the last Pokémon''s appeal is the same type as this move, user earns six points instead of two.', 12, 9),
(13, 'Always adds a point to the applause meter, regardless of whether the move matches the contest, and can likewise gain the applause bonus.', 13, 9),
(14, 'Attempts to jam all Pokémon that have appealed this turn for half their appeal points (minimum 1).', 14, 9),
(15, 'Prevents jamming for the rest of this turn.', 15, 9),
(16, 'Prevents the next jam on this turn.', 16, 9),
(17, 'Repeated use does not incur a penalty.', 17, 9),
(18, 'Attempts to make all following Pokémon nervous (and thus unable to appeal).', 18, 9),
(19, 'User earns appeal points equal to the points the previous Pokémon earned plus one.', 19, 9),
(20, 'User earns appeal points equal to half the points ALL the previous Pokémon earned plus one.', 20, 9),
(21, 'Shuffles the next turn''s turn order.', 21, 9),
(22, 'Cancels combo standby status for all Pokémon that have appealed this turn.', 22, 9),
(23, 'Attempts to jam all Pokémon that have appealed this turn. If a Pokémon used the same type move as this one, it is jammed for 4 points instead of 1.', 23, 9),
(24, 'Prevents the Applause Meter from rising for the rest of the turn.', 24, 9),
(25, 'Randomly earns one, two, four, or eight points.', 25, 9),
(26, 'If user appeals first this turn, earns one point; if second, two points; if third, four points; if last, six points.', 26, 9),
(27, 'If user appeals first this turn, earns six points instead of two.', 27, 9),
(28, 'If user appeals last this turn, earns six points instead of two.', 28, 9),
(29, 'If user has no stars, earns one point; if one, three points; if two, five points; if three, seven points. This does not include the appeal point bonus the stars give.', 29, 9),
(30, 'User will go first next turn.', 30, 9),
(31, 'User will go last next turn.', 31, 9),
(32, 'User gains one star.', 32, 9),
(33, 'Removes all stars from all Pokémon that have appealed this turn.', 33, 9);
