CREATE TABLE contests_effects_flavors_text_lang (
    id INT PRIMARY KEY,
    flavor_text VARCHAR(300) NOT NULL,
    contest_effect_id INT,
    language_id INT,
    FOREIGN KEY (contest_effect_id) REFERENCES contests_effects(id),
    FOREIGN KEY (language_id) REFERENCES languages(id)
);


-- Inglese (già inseriti)
INSERT INTO contests_effects_flavors_text_lang (id, flavor_text, contest_effect_id, language_id) VALUES 
(1, 'A highly appealing move.', 1, 9),
(2, 'Affected by how well the appeal in front goes.', 2, 9),
(3, 'After this move, the user is more easily startled.', 3, 9),
(4, 'Badly startles the Pokémon in front.', 4, 9),
(5, 'Badly startles those that have made appeals.', 5, 9),
(6, 'Jams the others, and misses one turn of appeals.', 6, 9),
(7, 'Makes a great appeal, but allows no more to the end.', 7, 9),
(8, 'Startles all Pokémon that have done their appeals.', 8, 9),
(9, 'Startles the Pokémon that appealed before the user.', 9, 9),
(10, 'Startles the Pokémon that has the judge''s attention.', 10, 9),
(11, 'The appeal works best the more the crowd is excited.', 11, 9),
(12, 'Works well if it''s the same type as the one before.', 12, 9),
(13, 'An appeal that excites the audience in any contest.', 13, 9),
(14, 'Badly startles all Pokémon that made good appeals.', 14, 9),
(15, 'Can avoid being startled by others.', 15, 9),
(16, 'Can avoid being startled by others once.', 16, 9),
(17, 'Can be repeatedly used without boring the judge.', 17, 9),
(18, 'Makes all Pokémon after the user nervous.', 18, 9),
(19, 'Makes the appeal as good as the one before it.', 19, 9),
(20, 'Makes the appeal as good as those before it.', 20, 9),
(21, 'Scrambles up the order of appeals on the next turn.', 21, 9),
(22, 'Shifts the judge''s attention from others.', 22, 9),
(23, 'Startles Pokémon that made a same-type appeal.', 23, 9),
(24, 'Temporarily stops the crowd from getting excited.', 24, 9),
(25, 'The appeal''s quality depends on its timing.', 25, 9),
(26, 'The appeal works better the later it is performed.', 26, 9),
(27, 'The appeal works great if performed first.', 27, 9),
(28, 'The appeal works great if performed last.', 28, 9),
(29, 'The appeal works well if the user''s condition is good.', 29, 9),
(30, 'The next appeal can be made earlier next turn.', 30, 9),
(31, 'The next appeal can be made later next turn.', 31, 9),
(32, 'Ups the user''s condition. Helps prevent nervousness.', 32, 9),
(33, 'Worsens the condition of those that made appeals.', 33, 9);

-- Italiano
INSERT INTO contests_effects_flavors_text_lang (id, flavor_text, contest_effect_id, language_id) VALUES 
(34, 'Una mossa molto attraente.', 1, 8),
(35, 'Influenzato da quanto bene va l''appello precedente.', 2, 8),
(36, 'Dopo questa mossa, l''utente è più facilmente spaventato.', 3, 8),
(37, 'Spaventa gravemente il Pokémon davanti.', 4, 8),
(38, 'Spaventa gravemente quelli che hanno fatto appelli.', 5, 8),
(39, 'Blocca gli altri e perde un turno di appelli.', 6, 8),
(40, 'Fa un grande appello, ma non permette altri fino alla fine.', 7, 8),
(41, 'Spaventa tutti i Pokémon che hanno fatto i loro appelli.', 8, 8),
(42, 'Spaventa il Pokémon che ha fatto l''appello prima dell''utente.', 9, 8),
(43, 'Spaventa il Pokémon che ha l''attenzione del giudice.', 10, 8),
(44, 'L''appello funziona meglio quanto più il pubblico è eccitato.', 11, 8),
(45, 'Funziona bene se è dello stesso tipo di quello precedente.', 12, 8),
(46, 'Un appello che eccita il pubblico in qualsiasi concorso.', 13, 8),
(47, 'Spaventa gravemente tutti i Pokémon che hanno fatto buoni appelli.', 14, 8),
(48, 'Può evitare di essere spaventato dagli altri.', 15, 8),
(49, 'Può evitare di essere spaventato dagli altri una volta.', 16, 8),
(50, 'Può essere usato ripetutamente senza annoiare il giudice.', 17, 8),
(51, 'Rende nervosi tutti i Pokémon dopo l''utente.', 18, 8),
(52, 'Rende l''appello buono come quello precedente.', 19, 8),
(53, 'Rende l''appello buono come quelli precedenti.', 20, 8),
(54, 'Rimescola l''ordine degli appelli al turno successivo.', 21, 8),
(55, 'Sposta l''attenzione del giudice dagli altri.', 22, 8),
(56, 'Spaventa i Pokémon che hanno fatto un appello dello stesso tipo.', 23, 8),
(57, 'Impedisce temporaneamente al pubblico di eccitarsi.', 24, 8),
(58, 'La qualità dell''appello dipende dal suo tempismo.', 25, 8),
(59, 'L''appello funziona meglio più tardi viene eseguito.', 26, 8),
(60, 'L''appello funziona alla grande se eseguito per primo.', 27, 8),
(61, 'L''appello funziona alla grande se eseguito per ultimo.', 28, 8),
(62, 'L''appello funziona bene se la condizione dell''utente è buona.', 29, 8),
(63, 'Il prossimo appello può essere fatto prima al turno successivo.', 30, 8),
(64, 'Il prossimo appello può essere fatto più tardi al turno successivo.', 31, 8),
(65, 'Migliora la condizione dell''utente. Aiuta a prevenire la nervosità.', 32, 8),
(66, 'Peggiora la condizione di quelli che hanno fatto appelli.', 33, 8);

-- Francese
INSERT INTO contests_effects_flavors_text_lang (id, flavor_text, contest_effect_id, language_id) VALUES 
(67, 'Une action très attrayante.', 1, 5),
(68, 'Affecté par la qualité de l''appel précédent.', 2, 5),
(69, 'Après cette action, l''utilisateur est plus facilement effrayé.', 3, 5),
(70, 'Effraie gravement le Pokémon devant.', 4, 5),
(71, 'Effraie gravement ceux qui ont fait des appels.', 5, 5),
(72, 'Bloque les autres et manque un tour d''appels.', 6, 5),
(73, 'Fait un grand appel, mais ne permet plus jusqu''à la fin.', 7, 5),
(74, 'Effraie tous les Pokémon qui ont fait leurs appels.', 8, 5),
(75, 'Effraie le Pokémon qui a fait l''appel avant l''utilisateur.', 9, 5),
(76, 'Effraie le Pokémon qui a l''attention du juge.', 10, 5),
(77, 'L''appel fonctionne mieux plus le public est excité.', 11, 5),
(78, 'Fonctionne bien si c''est du même type que celui d''avant.', 12, 5),
(79, 'Un appel qui excite le public dans n''importe quel concours.', 13, 5),
(80, 'Effraie gravement tous les Pokémon qui ont fait de bons appels.', 14, 5),
(81, 'Peut éviter d''être effrayé par les autres.', 15, 5),
(82, 'Peut éviter d''être effrayé par les autres une fois.', 16, 5),
(83, 'Peut être utilisé de manière répétée sans ennuyer le juge.', 17, 5),
(84, 'Rend nerveux tous les Pokémon après l''utilisateur.', 18, 5),
(85, 'Rend l''appel aussi bon que celui d''avant.', 19, 5),
(86, 'Rend l''appel aussi bon que ceux d''avant.', 20, 5),
(87, 'Mélange l''ordre des appels au tour suivant.', 21, 5),
(88, 'Détourne l''attention du juge des autres.', 22, 5),
(89, 'Effraie les Pokémon qui ont fait un appel du même type.', 23, 5),
(90, 'Empêche temporairement la foule de s''exciter.', 24, 5),
(91, 'La qualité de l''appel dépend de son timing.', 25, 5),
(92, 'L''appel fonctionne mieux plus il est effectué tardivement.', 26, 5),
(93, 'L''appel fonctionne très bien s''il est effectué en premier.', 27, 5),
(94, 'L''appel fonctionne très bien s''il est effectué en dernier.', 28, 5),
(95, 'L''appel fonctionne bien si la condition de l''utilisateur est bonne.', 29, 5),
(96, 'Le prochain appel peut être fait plus tôt au tour suivant.', 30, 5),
(97, 'Le prochain appel peut être fait plus tard au tour suivant.', 31, 5),
(98, 'Améliore l''état de l''utilisateur. Aide à prévenir le stress.', 32, 5),
(99, 'Dégrade l''état de ceux qui ont fait des appels.', 33, 5);

--Spagnolo
INSERT INTO contests_effects_flavors_text_lang (id, flavor_text, contest_effect_id, language_id) VALUES 
(100, 'Un movimiento muy atractivo.', 1, 7),
(101, 'Afectado por lo bien que va el llamamiento anterior.', 2, 7),
(102, 'Después de este movimiento, el usuario se asusta más fácilmente.', 3, 7),
(103, 'Asusta gravemente al Pokémon delante.', 4, 7),
(104, 'Asusta gravemente a los que han hecho llamamientos.', 5, 7),
(105, 'Bloquea a los demás y pierde un turno de llamamientos.', 6, 7),
(106, 'Hace un gran llamamiento, pero no permite más hasta el final.', 7, 7),
(107, 'Asusta a todos los Pokémon que han hecho sus llamamientos.', 8, 7),
(108, 'Asusta al Pokémon que hizo el llamamiento antes del usuario.', 9, 7),
(109, 'Asusta al Pokémon que tiene la atención del juez.', 10, 7),
(110, 'El llamamiento funciona mejor cuanto más excitado está el público.', 11, 7),
(111, 'Funciona bien si es del mismo tipo que el anterior.', 12, 7),
(112, 'Un llamamiento que excita al público en cualquier concurso.', 13, 7),
(113, 'Asusta gravemente a todos los Pokémon que han hecho buenos llamamientos.', 14, 7),
(114, 'Puede evitar ser asustado por los demás.', 15, 7),
(115, 'Puede evitar ser asustado por los demás una vez.', 16, 7),
(116, 'Puede ser utilizado repetidamente sin aburrir al juez.', 17, 7),
(117, 'Pone nerviosos a todos los Pokémon después del usuario.', 18, 7),
(118, 'Hace que el llamamiento sea tan bueno como el anterior.', 19, 7),
(119, 'Hace que el llamamiento sea tan bueno como los anteriores.', 20, 7),
(120, 'Mezcla el orden de los llamamientos en el siguiente turno.', 21, 7),
(121, 'Desvía la atención del juez de los demás.', 22, 7),
(122, 'Asusta a los Pokémon que hicieron un llamamiento del mismo tipo.', 23, 7),
(123, 'Impide temporalmente que la multitud se emocione.', 24, 7),
(124, 'La calidad del llamamiento depende de su temporización.', 25, 7),
(125, 'El llamamiento funciona mejor cuanto más tarde se realiza.', 26, 7),
(126, 'El llamamiento funciona muy bien si se realiza primero.', 27, 7),
(127, 'El llamamiento funciona muy bien si se realiza al final.', 28, 7),
(128, 'El llamamiento funciona bien si la condición del usuario es buena.', 29, 7),
(129, 'El próximo llamamiento puede hacerse antes en el siguiente turno.', 30, 7),
(130, 'El próximo llamamiento puede hacerse más tarde en el siguiente turno.', 31, 7),
(131, 'Mejora la condición del usuario. Ayuda a prevenir los nervios.', 32, 7),
(132, 'Empeora la condición de aquellos que han hecho llamamientos.', 33, 7);


--Tedesco
INSERT INTO contests_effects_flavors_text_lang (id, flavor_text, contest_effect_id, language_id) VALUES 
(133, 'Eine sehr ansprechende Bewegung.', 1, 6),
(134, 'Beeinflusst, wie gut der vorherige Aufruf verlief.', 2, 6),
(135, 'Nach dieser Bewegung wird der Benutzer leichter erschreckt.', 3, 6),
(136, 'Erschreckt schwer das Pokémon davor.', 4, 6),
(137, 'Erschreckt schwer diejenigen, die Aufrufe gemacht haben.', 5, 6),
(138, 'Blockiert die anderen und verpasst eine Runde Aufrufe.', 6, 6),
(139, 'Macht einen großartigen Aufruf, erlaubt aber keinen weiteren bis zum Ende.', 7, 6),
(140, 'Erschreckt alle Pokémon, die ihre Aufrufe gemacht haben.', 8, 6),
(141, 'Erschreckt das Pokémon, das vor dem Benutzer den Aufruf gemacht hat.', 9, 6),
(142, 'Erschreckt das Pokémon, das die Aufmerksamkeit des Richters hat.', 10, 6),
(143, 'Der Aufruf funktioniert am besten, je mehr die Menge aufgeregt ist.', 11, 6),
(144, 'Funktioniert gut, wenn es derselbe Typ ist wie der vorherige.', 12, 6),
(145, 'Ein Aufruf, der das Publikum bei jedem Wettbewerb begeistert.', 13, 6),
(146, 'Erschreckt schwer alle Pokémon, die gute Aufrufe gemacht haben.', 14, 6),
(147, 'Kann vermeiden, von anderen erschreckt zu werden.', 15, 6),
(148, 'Kann einmal vermeiden, von anderen erschreckt zu werden.', 16, 6),
(149, 'Kann wiederholt verwendet werden, ohne den Richter zu langweilen.', 17, 6),
(150, 'Macht alle Pokémon nach dem Benutzer nervös.', 18, 6),
(151, 'Macht den Aufruf so gut wie den vorherigen.', 19, 6),
(152, 'Macht den Aufruf so gut wie alle vorherigen.', 20, 6),
(153, 'Mischt die Reihenfolge der Aufrufe in der nächsten Runde neu.', 21, 6),
(154, 'Lenkt die Aufmerksamkeit des Richters von den anderen ab.', 22, 6),
(155, 'Erschreckt die Pokémon, die einen Aufruf vom selben Typ gemacht haben.', 23, 6),
(156, 'Verhindert vorübergehend, dass die Menge aufgeregt wird.', 24, 6),
(157, 'Die Qualität des Aufrufs hängt von seinem Timing ab.', 25, 6),
(158, 'Der Aufruf funktioniert besser, je später er ausgeführt wird.', 26, 6),
(159, 'Der Aufruf funktioniert hervorragend, wenn er zuerst ausgeführt wird.', 27, 6),
(160, 'Der Aufruf funktioniert hervorragend, wenn er zuletzt ausgeführt wird.', 28, 6),
(161, 'Der Aufruf funktioniert gut, wenn die Bedingung des Benutzers gut ist.', 29, 6),
(162, 'Der nächste Aufruf kann in der nächsten Runde früher erfolgen.', 30, 6),
(163, 'Der nächste Aufruf kann in der nächsten Runde später erfolgen.', 31, 6),
(164, 'Verbessert die Bedingung des Benutzers. Hilft Nervosität zu verhindern.', 32, 6),
(165, 'Verschlechtert die Bedingung derjenigen, die Aufrufe gemacht haben.', 33, 6);


--Giapponese
INSERT INTO contests_effects_flavors_text_lang (id, flavor_text, contest_effect_id, language_id) VALUES 
(166, '非常に魅力的な動きです。', 1, 1),
(167, '前のアピールがどれほど上手くいったかに影響されます。', 2, 1),
(168, 'この動きの後、ユーザーはより簡単に驚かされます。', 3, 1),
(169, '前のポケモンをひどく驚かせます。', 4, 1),
(170, 'アピールを行ったポケモンをひどく驚かせます。', 5, 1),
(171, '他のポケモンをジャムし、アピールターンを1つ失います。', 6, 1),
(172, '素晴らしいアピールをしますが、最後までこれ以上のアピールはできません。', 7, 1),
(173, 'アピールを行ったすべてのポケモンを驚かせます。', 8, 1),
(174, 'ユーザーの前にアピールしたポケモンを驚かせます。', 9, 1),
(175, '審査員の注意を引いたポケモンを驚かせます。', 10, 1),
(176, '群衆が興奮するほどアピールがうまくいきます。', 11, 1),
(177, '前と同じタイプであれば効果的です。', 12, 1),
(178, 'どんなコンテストでも観客を興奮させるアピールです。', 13, 1),
(179, '良いアピールをしたすべてのポケモンをひどく驚かせます。', 14, 1),
(180, '他のポケモンに驚かされることを避けられます。', 15, 1),
(181, '一度だけ他のポケモンに驚かされることを避けられます。', 16, 1),
(182, '審査員を退屈させることなく繰り返し使用できます。', 17, 1),
(183, 'ユーザーの後のすべてのポケモンを緊張させます。', 18, 1),
(184, 'アピールが前と同じくらい良くなります。', 19, 1),
(185, 'すべての前のアピールと同じくらい良くなります。', 20, 1),
(186, '次のターンのアピール順をシャッフルします。', 21, 1),
(187, '他のポケモンから審査員の注意を逸らします。', 22, 1),
(188, '同じタイプのアピールをしたポケモンを驚かせます。', 23, 1),
(189, '一時的に群衆が興奮しないようにします。', 24, 1),
(190, 'アピールの質はタイミングに依存します。', 25, 1),
(191, '後で行うほどアピールがうまくいきます。', 26, 1),
(192, '最初に行われるとアピールが優れています。', 27, 1),
(193, '最後に行われるとアピールが優れています。', 28, 1),
(194, 'ユーザーの状態が良ければアピールがうまくいきます。', 29, 1),
(195, '次のターンでアピールを早く行えます。', 30, 1),
(196, '次のターンでアピールを遅く行えます。', 31, 1),
(197, 'ユーザーの状態を向上させます。緊張を防ぐのに役立ちます。', 32, 1),
(198, 'アピールを行ったポケモンの状態を悪化させます。', 33, 1);
