CREATE TABLE encounters_names_lang (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    encounter_method_id INTEGER,
    language_id INTEGER,
    FOREIGN KEY (encounter_method_id) REFERENCES encounter_methods(id),
    FOREIGN KEY (language_id) REFERENCES languages(id)
);

INSERT INTO encounters_names_lang (id, name, encounter_method_id, language_id) VALUES 
(1, 'Im hohen Gras oder in einer Höhle laufen', 1, 6),
(2, 'Walking in tall grass or a cave', 1, 9),
(3, 'En marchant dans les herbes hautes ou une grotte', 1, 5),
(4, 'Mit einer normalen Angel angeln', 2, 6),
(5, 'Fishing with an Old Rod', 2, 9),
(6, 'En pêchant avec une Canne', 2, 5),
(7, 'Mit einer Profiangel angeln', 3, 6),
(8, 'Fishing with a Good Rod', 3, 9),
(9, 'En pêchant avec une Super Canne', 3, 5),
(10, 'Mit einer Superangel angeln', 4, 6),
(11, 'Fishing with a Super Rod', 4, 9),
(12, 'En pêchant avec une Méga Canne', 4, 5),
(13, 'Surfen', 5, 6),
(14, 'Surfing', 5, 9),
(15, 'En surfant', 5, 5),
(16, 'Steine zertrümmern', 6, 6),
(17, 'Smashing rocks', 6, 9),
(18, 'En brisant des rochers', 6, 5),
(19, 'Bäumen Kopfnüsse geben', 7, 6),
(20, 'Headbutting trees', 7, 9),
(21, 'En utilisant Coup d’Boule sur un arbre', 7, 5),
(22, 'Im dunklen Gras laufen', 8, 6),
(23, 'Walking in dark grass', 8, 9),
(24, 'En marchant dans les herbes sombres', 8, 5),
(25, 'Im raschelndem Gras laufen', 9, 6),
(26, 'Walking in rustling grass', 9, 9),
(27, 'En marchant dans les herbes mouvantes', 9, 5),
(28, 'In Staubwolken laufen', 10, 6),
(29, 'Walking in dust clouds', 10, 9),
(30, 'En marchant dans un nuage de poussière', 10, 5),
(31, 'Im Schatten einer Brücke laufen', 11, 6),
(32, 'Walking in bridge shadows', 11, 9),
(33, 'En marchant à l’ombre d’un pont', 11, 5),
(34, 'An dunklen stellen angeln', 12, 6),
(35, 'Fishing in dark spots', 12, 9),
(36, 'En pêchant dans les endroits sombres', 12, 5),
(37, 'An dunklen stellen surfen', 13, 6),
(38, 'Surfing in dark spots', 13, 9),
(39, 'En surfant sur les endroits sombres', 13, 5),
(40, 'In gelben Blumenfeldern laufen', 14, 6),
(41, 'Walking in yellow flowers', 14, 9),
(42, 'En marchant dans les fleurs jaunes', 14, 5),
(43, 'In violetten Blumenfeldern laufen', 15, 6),
(44, 'Walking in purple flowers', 15, 9),
(45, 'En marchant dans les fleurs violettes', 15, 5),
(46, 'In roten Blumenfeldern laufen', 16, 6),
(47, 'Walking in red flowers', 16, 9),
(48, 'En marchant dans les fleurs rouges', 16, 5),
(49, 'Auf unwegsamen Gelände laufen', 17, 6),
(50, 'Walking on rough terrain', 17, 9),
(51, 'En marchant sur un terrain accidenté', 17, 5),
(52, 'Receive as a gift', 18, 9),
(53, 'Reçu en cadeau', 18, 5),
(54, 'Receive egg as a gift', 19, 9),
(55, 'Œuf reçu en cadeau', 19, 5),
(56, 'Static encounter, only one chance', 20, 9),
(57, 'Rencontre statique, chance unique', 20, 5),
(58, 'Playing Pokéflute', 21, 9),
(59, 'En jouant de la Pokéflûte', 21, 5),
(60, 'Headbutting a low encounter rate tree', 22, 9),
(61, 'En utilisant Coup d’Boule sur un arbre à taux bas', 22, 5),
(62, 'Headbutting a normal encounter rate tree', 23, 9),
(63, 'En utilisant Coup d’Boule sur un arbre à taux normal', 23, 5),
(64, 'Headbutting a high encounter rate tree', 24, 9),
(65, 'En utilisant Coup d’Boule sur un arbre à taux élevé', 24, 5),
(66, 'Using the Squirt Bottle on a Sudowoodo', 25, 9),
(67, 'En utilisant la Carapuce à O sur Simularbre', 25, 5),
(68, 'Using the Wailmer Pail on a Sudowoodo', 26, 9),
(69, 'En utilisant le Seau Wailmer / Wailmerrosoir sur Simularbre', 26, 5),
(70, 'Diving on seaweed', 27, 9),
(71, 'En plongeant dans les algues', 27, 5),
(72, 'On any overworld patch of grass', 28, 9),
(73, 'Dans les herbes', 28, 5),
(74, 'On any overworld water tile', 29, 9),
(75, 'Sur l’eau', 29, 5),
(76, 'Using Devon Scope', 30, 9),
(77, 'En utilisant le Devon Scope', 30, 5),
(78, 'Fishing in a Feebas Tile', 31, 9),
(79, 'En pêchant sur une tuile à Barpau', 31, 5);

