CREATE TABLE moves_attributes_descriptions_lang (
    id INT PRIMARY KEY,
    description VARCHAR(500) NOT NULL,
    language_id INT,
    move_attribute_id INT,
    FOREIGN KEY (language_id) REFERENCES languages(id),
    FOREIGN KEY (move_attribute_id) REFERENCES moves_attributes(id)
);


INSERT INTO moves_attributes_descriptions_lang (id, description, language_id, move_attribute_id) VALUES 
(1, 'Der Anwender berührt das Ziel. Dies löst manche Fähigkeiten aus (z.B. static) und Gegenstände (z.B. sticky barb).', 6, 1),
(2, 'User touches the target. This triggers some abilities (e.g., static) and items (e.g., sticky barb).', 9, 1),
(3, 'Diese Fähigkeit hat eine Aufladerunde, welche mit einer power herb übersprungen werden kann.', 6, 2),
(4, 'This move has a charging turn that can be skipped with a power herb.', 9, 2),
(5, 'Die Runde nach dieser Fähigkeit wird benötigt, damit das Pokémon sich aufladen kann.', 6, 3),
(6, 'The turn after this move is used, the Pokémon''s action is skipped so it can recharge.', 9, 3),
(7, 'Diese Fähigkeit funktioniert nicht, wenn das Ziel detect oder protect diese Runde genutzt hat.', 6, 4),
(8, 'This move will not work if the target has used detect or protect this turn.', 9, 4),
(9, 'Diese Fähigkeit könnte reflektiert mit magic coat oder magic bounce reflektiert werden.', 6, 5),
(10, 'This move may be reflected back at the user with magic coat or magic bounce.', 9, 5),
(11, 'Diese Fähigkeit kann übernommen werden, wenn ein anderes Pokémon snatch diese Runde nutzt.', 6, 6),
(12, 'This move will be stolen if another Pokémon has used snatch this turn.', 9, 6),
(13, 'Ein von dieser Fähigkeit getroffenes Pokémon kann mirror move nutzen um diese Fähigkeit zu kopieren.', 6, 7),
(14, 'A Pokémon targeted by this move can use mirror move to copy it.', 9, 7),
(15, 'Diese Fähigkeit hat die 1.2× Kraft, wenn es von einem Pokémon mit iron fist genutzt wird.', 6, 8),
(16, 'This move has 1.2× its usual power when used by a Pokémon with iron fist.', 9, 8),
(17, 'Pokémon mit soundproof sind immun gegen diese Fähigkeit.', 6, 9),
(18, 'Pokémon with soundproof are immune to this move.', 9, 9),
(19, 'Diese Fähigkeit kann nicht bei hoher gravity genutzt werden.', 6, 10),
(20, 'This move cannot be used in high gravity.', 9, 10),
(21, 'Diese Fähigkeit kann genutzt werden, wenn das Pokémon vereist ist um es zu enteisen.', 6, 11),
(22, 'This move can be used while frozen to force the Pokémon to defrost.', 9, 11),
(23, 'In 3er Kämpfen trifft diese Fähigkeit den entferntesten Gegner.', 6, 12),
(24, 'In triple battles, this move can be used on either side to target the farthest away opposing Pokémon.', 9, 12),
(25, 'Diese Fähigkeit wird von heal block blockiert.', 6, 13),
(26, 'This move is blocked by heal block.', 9, 13),
(27, 'Diese Fähigkeit ignoriert den substitute des Ziels.', 6, 14),
(28, 'This move ignores the target''s substitute.', 9, 14),
(29, 'Pokémon mit overcoat und grass-Pokémon sind immun gegen diese Fähigkeit.', 6, 15),
(30, 'Pokémon with overcoat and grass-type Pokémon are immune to this move.', 9, 15),
(31, 'Diese Fähigkeit hat die 1.5× Kraft, wenn sie von einem Pokémon mit strong jaw genutzt wird.', 6, 16),
(32, 'This move has 1.5× its usual power when used by a Pokémon with strong jaw.', 9, 16),
(33, 'Diese Fähigkeit hat die 1.5× Kraft, wenn sie von einem Pokémon mit mega launcher genutzt wird.', 6, 17),
(34, 'This move has 1.5× its usual power when used by a Pokémon with mega launcher.', 9, 17),
(35, 'Diese Fähigkeit wird von bulletproof blockiert.', 6, 18),
(36, 'This move is blocked by bulletproof.', 9, 18),
(37, 'Diese Fähigkeit wird durch aroma veil blockiert und wird durch mental herb geheilt.', 6, 19),
(38, 'This move is blocked by aroma veil and cured by mental herb.', 9, 19),
(39, 'Diese Fähigkeit ist in Himmelskämpfen nicht nutzbar.', 6, 20),
(40, 'This move is unusable during Sky Battles.', 9, 20),
(41, 'This move triggers dancer.', 9, 21);
