CREATE TABLE pokedex_descriptions (
    id INT PRIMARY KEY,
    description VARCHAR(500) NOT NULL,
    language_id INT,
    pokedex_id INT,
    FOREIGN KEY (language_id) REFERENCES languages(id),
    FOREIGN KEY (pokedex_id) REFERENCES pokedex(id)
);

INSERT INTO pokedex_descriptions (id, description, language_id, pokedex_id) VALUES 
(1, "Pokédex National complet", 5, 1),
(2, "Komplette Nationale Dex", 6, 1),
(3, "Pokédex Nacional completa", 7, 1),
(4, "Entire National dex", 9, 1),
(5, "Pokédex régional de Kanto dans Rouge/Bleu/Jaune", 5, 2),
(6, "Rot/Blau/Gelb Kanto Dex", 6, 2),
(7, "Pokédex regional de Rojo/Azul/Amarillo", 7, 2),
(8, "Red/Blue/Yellow Kanto dex", 9, 2),
(9, "Pokédex régional de Johto dans Or/Argent/Cristal, appellé 'Nouveau' Pokédex dans le jeu", 5, 3),
(10, "Gold/Silber/Kristall Johto Dex — Auch der 'Neue' Pokédex im Spiel genannt", 6, 3),
(11, "Gold/Silver/Crystal Johto dex—called the 'New' Pokédex in-game", 9, 3),
(12, "Pokédex régional d'Hoenn dans Rubis/Saphir/Émeraude", 5, 4),
(13, "Rubin/Saphir/Smaragd Hoenn Dex", 6, 4),
(14, "Ruby/Sapphire/Emerald Hoenn dex", 9, 4),
(15, "Pokédex régional de Sinnoh dans Diamant/Perle", 5, 5),
(16, "Diamant/Perl Sinnoh Dex", 6, 5),
(17, "Diamond/Pearl Sinnoh dex", 9, 5),
(18, "Pokédex régional de Sinnoh dans Platine", 5, 6),
(19, "Platin Sinnoh Dex — eine erweiterte Version von Diamant und Perl", 6, 6),
(20, "Platinum Sinnoh dex—an extended version of Diamond and Pearl's", 9, 6),
(21, "Pokédex régional de Johto dans Or HeartGold/Argent SoulSilver, mis à jour pour la 4ème génération", 5, 7),
(22, "HeartGold/SoulSilver Johto Dex — Dex aus Gold/Silber/Kristall um Fähigkeiten basierende Entwicklungen aus Generation IV erweitert", 6, 7),
(23, "HeartGold/SoulSilver Johto dex—Gold/Silver/Crystal's, extended to add move-based Generation IV evolutions", 9, 7),
(24, "Pokédex régional d'Unys dans Noir/Blanc", 5, 8),
(25, "Schwarz/Weiß Einall Dex", 6, 8),
(26, "Black/White Unova dex", 9, 8),
(27, "Pokédex régional d'Unys dans Noir 2/Blanc 2", 5, 9),
(28, "Schwarz 2/Weiß 2 Einall Dex", 6, 9),
(29, "Black 2/White 2 Unova dex", 9, 9),
(30, "Ordre de la Galerie dans Pokémon Conquest", 5, 11),
(31, "Pokémon Conquest Galerie Reihenfolge", 6, 11),
(32, "Pokémon Conquest gallery order", 9, 11),
(33, '', 5, 12),
(34, '', 6, 12),
(35, '', 9, 12),
(36, '', 5, 13),
(37, '', 6, 13),
(38, '', 9, 13),
(39, '', 5, 14),
(40, '', 6, 14),
(41, '', 9, 14),
(42, "Pokédex régional d'Hoenn dans Rubis Oméga/Saphir Alpha, mis à jour pour les nouvelles évolutions", 5, 15),
(43, "Omega Rubin/Alpha Saphir Hoenn Dex — Dex aus Rubin/Saphir/Smaragd um Neue Entwicklungen erweitert", 6, 15),
(44, "Omega Ruby/Alpha Sapphire Hoenn Dex—Ruby/Sapphire/Emerald's, updated to add new evolutions", 9, 15),
(45, "Sun/Moon Alola dex", 9, 16),
(46, "Sun/Moon Melemele dex", 9, 17),
(47, "Sun/Moon Akala dex", 9, 18),
(48, "Sun/Moon Ula'ula dex", 9, 19),
(49, "Sun/Moon Poni dex", 9, 20),
(50, "Ultra Sun/Ultra Moon Alola dex", 9, 21),
(51, "Ultra Sun/Ultra Moon Melemele dex", 9, 22),
(52, "Ultra Sun/Ultra Moon Akala dex", 9, 23),
(53, "Ultra Sun/Ultra Moon Ula'ula dex", 9, 24),
(54, "Ultra Sun/Ultra Moon Poni dex", 9, 25),
(55, "Let’s Go: Pikachu/Let’s Go: Eevee Kanto dex", 9, 26),
(56, "Sword/Shield Galar dex", 9, 27),
(57, "Isle of Armor dex", 9, 28),
(58, "Crown Tundra dex", 9, 29),
(59, "Hisui dex", 9, 30),
(60, "Paldea dex", 9, 31);
