CREATE TABLE TypesSprites_new (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    TypeId INTEGER NOT NULL,
    VersionsGroupId INTEGER NOT NULL,
    Sprite BLOB,
    FOREIGN KEY (TypeId) REFERENCES Types(Id),
    FOREIGN KEY (VersionsGroupId) REFERENCES VersionsGroups(Id)
);

INSERT INTO TypesSprites_new (TypeId, VersionsGroupId)
VALUES
    (1, 11), -- generation-v > black-white
    (1, 14), -- generation-v > black-2-white-2
    (1, 9),  -- generation-iv > platinum
    (1, 8),  -- generation-iv > diamond-pearl
    (1, 10), -- generation-iv > heartgold-soulsilver
    (1, 25), -- generation-ix > scarlet-violet
    (1, 15), -- generation-vi > x-y
    (1, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (1, 12), -- generation-iii > xd
    (1, 6),  -- generation-iii > emerald
    (1, 7),  -- generation-iii > colosseum
    (1, 5),  -- generation-iii > ruby-sapphire
    (1, 7),  -- generation-iii > firered-leafgreen
    (1, 17), -- generation-vii > sun-moon
    (1, 18), -- generation-vii > ultra-sun-ultra-moon
    (1, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (1, 20), -- generation-viii > sword-shield
    (1, 24), -- generation-viii > legends-arceus
    (1, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (2, 11), -- generation-v > black-white
    (2, 14), -- generation-v > black-2-white-2
    (2, 9),  -- generation-iv > platinum
    (2, 8),  -- generation-iv > diamond-pearl
    (2, 10), -- generation-iv > heartgold-soulsilver
    (2, 25), -- generation-ix > scarlet-violet
    (2, 15), -- generation-vi > x-y
    (2, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (2, 8),  -- generation-iii > xd
    (2, 6),  -- generation-iii > emerald
    (2, 7),  -- generation-iii > colosseum
    (2, 5),  -- generation-iii > ruby-sapphire
    (2, 7),  -- generation-iii > firered-leafgreen
    (2, 17), -- generation-vii > sun-moon
    (2, 18), -- generation-vii > ultra-sun-ultra-moon
    (2, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (2, 20), -- generation-viii > sword-shield
    (2, 24), -- generation-viii > legends-arceus
    (2, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (3, 11), -- generation-v > black-white
    (3, 14), -- generation-v > black-2-white-2
    (3, 9),  -- generation-iv > platinum
    (3, 8),  -- generation-iv > diamond-pearl
    (3, 10), -- generation-iv > heartgold-soulsilver
    (3, 25), -- generation-ix > scarlet-violet
    (3, 15), -- generation-vi > x-y
    (3, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (3, 8),  -- generation-iii > xd
    (3, 6),  -- generation-iii > emerald
    (3, 7),  -- generation-iii > colosseum
    (3, 5),  -- generation-iii > ruby-sapphire
    (3, 7),  -- generation-iii > firered-leafgreen
    (3, 17), -- generation-vii > sun-moon
    (3, 18), -- generation-vii > ultra-sun-ultra-moon
    (3, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (3, 20), -- generation-viii > sword-shield
    (3, 24), -- generation-viii > legends-arceus
    (3, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (4, 11), -- generation-v > black-white
    (4, 14), -- generation-v > black-2-white-2
    (4, 9),  -- generation-iv > platinum
    (4, 8),  -- generation-iv > diamond-pearl
    (4, 10), -- generation-iv > heartgold-soulsilver
    (4, 25), -- generation-ix > scarlet-violet
    (4, 15), -- generation-vi > x-y
    (4, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (4, 12), -- generation-iii > xd
    (4, 6),  -- generation-iii > emerald
    (4, 7),  -- generation-iii > colosseum
    (4, 5),  -- generation-iii > ruby-sapphire
    (4, 7),  -- generation-iii > firered-leafgreen
    (4, 17), -- generation-vii > sun-moon
    (4, 18), -- generation-vii > ultra-sun-ultra-moon
    (4, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (4, 20), -- generation-viii > sword-shield
    (4, 24), -- generation-viii > legends-arceus
    (4, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (5, 11), -- generation-v > black-white
    (5, 14), -- generation-v > black-2-white-2
    (5, 9),  -- generation-iv > platinum
    (5, 8),  -- generation-iv > diamond-pearl
    (5, 10), -- generation-iv > heartgold-soulsilver
    (5, 25), -- generation-ix > scarlet-violet
    (5, 15), -- generation-vi > x-y
    (5, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (5, 12), -- generation-iii > xd
    (5, 6),  -- generation-iii > emerald
    (5, 7),  -- generation-iii > colosseum
    (5, 5),  -- generation-iii > ruby-sapphire
    (5, 7),  -- generation-iii > firered-leafgreen
    (5, 17), -- generation-vii > sun-moon
    (5, 18), -- generation-vii > ultra-sun-ultra-moon
    (5, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (5, 20), -- generation-viii > sword-shield
    (5, 24), -- generation-viii > legends-arceus
    (5, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (6, 11), -- generation-v > black-white
    (6, 14), -- generation-v > black-2-white-2
    (6, 9),  -- generation-iv > platinum
    (6, 8),  -- generation-iv > diamond-pearl
    (6, 10), -- generation-iv > heartgold-soulsilver
    (6, 25), -- generation-ix > scarlet-violet
    (6, 15), -- generation-vi > x-y
    (6, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (6, 12), -- generation-iii > xd
    (6, 6),  -- generation-iii > emerald
    (6, 7),  -- generation-iii > colosseum
    (6, 5),  -- generation-iii > ruby-sapphire
    (6, 7),  -- generation-iii > firered-leafgreen
    (6, 17), -- generation-vii > sun-moon
    (6, 18), -- generation-vii > ultra-sun-ultra-moon
    (6, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (6, 20), -- generation-viii > sword-shield
    (6, 24), -- generation-viii > legends-arceus
    (6, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (7, 11), -- generation-v > black-white
    (7, 14), -- generation-v > black-2-white-2
    (7, 9),  -- generation-iv > platinum
    (7, 8),  -- generation-iv > diamond-pearl
    (7, 10), -- generation-iv > heartgold-soulsilver
    (7, 25), -- generation-ix > scarlet-violet
    (7, 15), -- generation-vi > x-y
    (7, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (7, 12), -- generation-iii > xd
    (7, 6),  -- generation-iii > emerald
    (7, 7),  -- generation-iii > colosseum
    (7, 5),  -- generation-iii > ruby-sapphire
    (7, 7),  -- generation-iii > firered-leafgreen
    (7, 17), -- generation-vii > sun-moon
    (7, 18), -- generation-vii > ultra-sun-ultra-moon
    (7, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (7, 20), -- generation-viii > sword-shield
    (7, 24), -- generation-viii > legends-arceus
    (7, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (8, 11), -- generation-v > black-white
    (8, 14), -- generation-v > black-2-white-2
    (8, 9),  -- generation-iv > platinum
    (8, 8),  -- generation-iv > diamond-pearl
    (8, 10), -- generation-iv > heartgold-soulsilver
    (8, 25), -- generation-ix > scarlet-violet
    (8, 15), -- generation-vi > x-y
    (8, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (8, 12), -- generation-iii > xd
    (8, 6),  -- generation-iii > emerald
    (8, 7),  -- generation-iii > colosseum
    (8, 5),  -- generation-iii > ruby-sapphire
    (8, 7),  -- generation-iii > firered-leafgreen
    (8, 17), -- generation-vii > sun-moon
    (8, 18), -- generation-vii > ultra-sun-ultra-moon
    (8, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (8, 20), -- generation-viii > sword-shield
    (8, 24), -- generation-viii > legends-arceus
    (8, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (9, 11), -- generation-v > black-white
    (9, 14), -- generation-v > black-2-white-2
    (9, 9),  -- generation-iv > platinum
    (9, 8),  -- generation-iv > diamond-pearl
    (9, 10), -- generation-iv > heartgold-soulsilver
    (9, 25), -- generation-ix > scarlet-violet
    (9, 15), -- generation-vi > x-y
    (9, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (9, 12), -- generation-iii > xd
    (9, 6),  -- generation-iii > emerald
    (9, 7),  -- generation-iii > colosseum
    (9, 5),  -- generation-iii > ruby-sapphire
    (9, 7),  -- generation-iii > firered-leafgreen
    (9, 17), -- generation-vii > sun-moon
    (9, 18), -- generation-vii > ultra-sun-ultra-moon
    (9, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (9, 20), -- generation-viii > sword-shield
    (9, 24), -- generation-viii > legends-arceus
    (9, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (10, 11), -- generation-v > black-white
    (10, 14), -- generation-v > black-2-white-2
    (10, 9),  -- generation-iv > platinum
    (10, 8),  -- generation-iv > diamond-pearl
    (10, 10), -- generation-iv > heartgold-soulsilver
    (10, 25), -- generation-ix > scarlet-violet
    (10, 15), -- generation-vi > x-y
    (10, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (10, 12), -- generation-iii > xd
    (10, 6),  -- generation-iii > emerald
    (10, 7),  -- generation-iii > colosseum
    (10, 5),  -- generation-iii > ruby-sapphire
    (10, 7),  -- generation-iii > firered-leafgreen
    (10, 17), -- generation-vii > sun-moon
    (10, 18), -- generation-vii > ultra-sun-ultra-moon
    (10, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (10, 20), -- generation-viii > sword-shield
    (10, 24), -- generation-viii > legends-arceus
    (10, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (11, 11), -- generation-v > black-white
    (11, 14), -- generation-v > black-2-white-2
    (11, 9),  -- generation-iv > platinum
    (11, 8),  -- generation-iv > diamond-pearl
    (11, 10), -- generation-iv > heartgold-soulsilver
    (11, 25), -- generation-ix > scarlet-violet
    (11, 15), -- generation-vi > x-y
    (11, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (11, 12), -- generation-iii > xd
    (11, 6),  -- generation-iii > emerald
    (11, 7),  -- generation-iii > colosseum
    (11, 5),  -- generation-iii > ruby-sapphire
    (11, 7),  -- generation-iii > firered-leafgreen
    (11, 17), -- generation-vii > sun-moon
    (11, 18), -- generation-vii > ultra-sun-ultra-moon
    (11, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (11, 20), -- generation-viii > sword-shield
    (11, 24), -- generation-viii > legends-arceus
    (11, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (12, 11), -- generation-v > black-white
    (12, 14), -- generation-v > black-2-white-2
    (12, 9),  -- generation-iv > platinum
    (12, 8),  -- generation-iv > diamond-pearl
    (12, 10), -- generation-iv > heartgold-soulsilver
    (12, 25), -- generation-ix > scarlet-violet
    (12, 15), -- generation-vi > x-y
    (12, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (12, 12), -- generation-iii > xd
    (12, 6),  -- generation-iii > emerald
    (12, 7),  -- generation-iii > colosseum
    (12, 5),  -- generation-iii > ruby-sapphire
    (12, 7),  -- generation-iii > firered-leafgreen
    (12, 17), -- generation-vii > sun-moon
    (12, 18), -- generation-vii > ultra-sun-ultra-moon
    (12, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (12, 20), -- generation-viii > sword-shield
    (12, 24), -- generation-viii > legends-arceus
    (12, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (13, 11), -- generation-v > black-white
    (13, 14), -- generation-v > black-2-white-2
    (13, 9),  -- generation-iv > platinum
    (13, 8),  -- generation-iv > diamond-pearl
    (13, 10), -- generation-iv > heartgold-soulsilver
    (13, 25), -- generation-ix > scarlet-violet
    (13, 15), -- generation-vi > x-y
    (13, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (13, 12), -- generation-iii > xd
    (13, 6),  -- generation-iii > emerald
    (13, 7),  -- generation-iii > colosseum
    (13, 5),  -- generation-iii > ruby-sapphire
    (13, 7),  -- generation-iii > firered-leafgreen
    (13, 17), -- generation-vii > sun-moon
    (13, 18), -- generation-vii > ultra-sun-ultra-moon
    (13, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (13, 20), -- generation-viii > sword-shield
    (13, 24), -- generation-viii > legends-arceus
    (13, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (14, 11), -- generation-v > black-white
    (14, 14), -- generation-v > black-2-white-2
    (14, 9),  -- generation-iv > platinum
    (14, 8),  -- generation-iv > diamond-pearl
    (14, 10), -- generation-iv > heartgold-soulsilver
    (14, 25), -- generation-ix > scarlet-violet
    (14, 15), -- generation-vi > x-y
    (14, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (14, 12), -- generation-iii > xd
    (14, 6),  -- generation-iii > emerald
    (14, 7),  -- generation-iii > colosseum
    (14, 5),  -- generation-iii > ruby-sapphire
    (14, 7),  -- generation-iii > firered-leafgreen
    (14, 17), -- generation-vii > sun-moon
    (14, 18), -- generation-vii > ultra-sun-ultra-moon
    (14, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (14, 20), -- generation-viii > sword-shield
    (14, 24), -- generation-viii > legends-arceus
    (14, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (15, 11), -- generation-v > black-white
    (15, 14), -- generation-v > black-2-white-2
    (15, 9),  -- generation-iv > platinum
    (15, 8),  -- generation-iv > diamond-pearl
    (15, 10), -- generation-iv > heartgold-soulsilver
    (15, 25), -- generation-ix > scarlet-violet
    (15, 15), -- generation-vi > x-y
    (15, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (15, 12), -- generation-iii > xd
    (15, 6),  -- generation-iii > emerald
    (15, 7),  -- generation-iii > colosseum
    (15, 5),  -- generation-iii > ruby-sapphire
    (15, 7),  -- generation-iii > firered-leafgreen
    (15, 17), -- generation-vii > sun-moon
    (15, 18), -- generation-vii > ultra-sun-ultra-moon
    (15, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (15, 20), -- generation-viii > sword-shield
    (15, 24), -- generation-viii > legends-arceus
    (15, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (16, 11), -- generation-v > black-white
    (16, 14), -- generation-v > black-2-white-2
    (16, 9),  -- generation-iv > platinum
    (16, 8),  -- generation-iv > diamond-pearl
    (16, 10), -- generation-iv > heartgold-soulsilver
    (16, 25), -- generation-ix > scarlet-violet
    (16, 15), -- generation-vi > x-y
    (16, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (16, 12), -- generation-iii > xd
    (16, 6),  -- generation-iii > emerald
    (16, 7),  -- generation-iii > colosseum
    (16, 5),  -- generation-iii > ruby-sapphire
    (16, 7),  -- generation-iii > firered-leafgreen
    (16, 17), -- generation-vii > sun-moon
    (16, 18), -- generation-vii > ultra-sun-ultra-moon
    (16, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (16, 20), -- generation-viii > sword-shield
    (16, 24), -- generation-viii > legends-arceus
    (16, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (17, 11), -- generation-v > black-white
    (17, 14), -- generation-v > black-2-white-2
    (17, 9),  -- generation-iv > platinum
    (17, 8),  -- generation-iv > diamond-pearl
    (17, 10), -- generation-iv > heartgold-soulsilver
    (17, 25), -- generation-ix > scarlet-violet
    (17, 15), -- generation-vi > x-y
    (17, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (17, 12), -- generation-iii > xd
    (17, 6),  -- generation-iii > emerald
    (17, 7),  -- generation-iii > colosseum
    (17, 5),  -- generation-iii > ruby-sapphire
    (17, 7),  -- generation-iii > firered-leafgreen
    (17, 17), -- generation-vii > sun-moon
    (17, 18), -- generation-vii > ultra-sun-ultra-moon
    (17, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (17, 20), -- generation-viii > sword-shield
    (17, 24), -- generation-viii > legends-arceus
    (17, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (18, 25), -- generation-ix > scarlet-violet
    (18, 15), -- generation-vi > x-y
    (18, 16), -- generation-vi > omega-ruby-alpha-sapphire
    (18, 17), -- generation-vii > sun-moon
    (18, 18), -- generation-vii > ultra-sun-ultra-moon
    (18, 19), -- generation-vii > lets-go-pikachu-lets-go-eevee
    (18, 20), -- generation-viii > sword-shield
    (18, 24), -- generation-viii > legends-arceus
    (18, 23), -- generation-viii > brilliant-diamond-and-shining-pearl
    (19, 25), -- generation-ix > scarlet-violet
    (10001, 9),  -- generation-iv > platinum
    (10001, 8),  -- generation-iv > diamond-pearl
    (10001, 10), -- generation-iv > heartgold-soulsilver
    (10001, 12), -- generation-iii > xd
    (10001, 6),  -- generation-iii > emerald
    (10001, 7),  -- generation-iii > colosseum
    (10001, 5),  -- generation-iii > ruby-sapphire
    (10001, 7);  -- generation-iii > firered-leafgreen

